#!/bin/bash
# Nagios plugin to monitor nic em2

percent=`df /var/ | sed -re 's/.* ([0-9]+)%.*/\\1/' | grep -E '^[0-9]'`


echo "$percent%"
if [ $percent -gt 90 ]
then
    exit 2
elif [ $percent -gt 80 ]
then
    exit 1
else
    exit 0
fi
