#!/bin/bash
# Nagios plugin to monitor glance gluster mount

data=$(/bin/mount | /bin/grep '/mnt/trystack')
rv=$?

if [ "$rv" != "0" ] ; then
    echo $data
    exit 2
fi

echo "$data" # | grep -v -e "^ID " -e "---------------" | wc -l

